# Generated by Django 5.2 on 2025-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='break_time',
            field=models.FloatField(default=0),
        ),
    ]
